[package]
name = "mnist-training"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.8.3"
candle-datasets = "0.8.3"
candle-nn = "0.8.3"
clap = { version = "4.5.31", features = ["derive"] }
rand = "0.9.0"
anyhow = "1.0.96"
